[package]
name = "pear-search"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
futures = "0.3.30"
json = "0.12.4"
reqwest = "0.12.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
